name: Deploy site
on:
  push:
    branches:
      - main

jobs:

  deploy-site:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - name: NPM Install
        working-directory: .
        run: |
          npm install
      - name: Run Eleventy
        working-directory: .
        run: |
          ./build.sh
      - name: Add .nojekyll
        working-directory: .
        run: |
          touch _site/.nojekyll
      - name: Add CNAME
        working-directory: .
        run: |
          echo 'ceramic-engine.com' > _site/CNAME
      - name: Deploy to Github Pages
        uses: ceramic-engine/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: _site
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
